GDQuest/learn-gdscript

- lsp/ScriptVerifier.gd
I think this added for debug purposes or printed message must be different then "sdfdsfdsf?" ?
> chore: remove debug print statement

- ui/components/Revealer.gd
#104
Also fix folding if animation disabled.
> fix: revealer animation folding

- ui/welcome_screen/WelcomeScreen.tscn
This small PR fixes wrong wording in the welcome screen. 
It changes the word "your" to "for" in the "Early beta release"-infobox.
This should fix issue #123.
Thanks to @duianto for helping me out! :)
> fix: typo on end screen

- addons/gdscript-course-builder/ui/QuizContentBlock.gd
- resources/QuizChoice.gd
Related issue (if applicable): #20 
Adds 1 variable and 2 new functions to QuizContentBlock.gd.
These are used to confirm with the user that the quiz type change is correct.
QuizChoice now has the "tool" keyword.
Not that I'm aware of.
Will proceed to change the quiz type if requested, without asking for confirmation.
Will now ask for confirmation about changing the quiz type and warn that current data may be lost.
Fixed a bug where the course builder didn't change the choice type due to QuizChoice not having the tool keyword …
> improvement: confirm quiz type change

- course/lesson-11-time-delta/lesson.tres
Fixed a typo.
Before:
>At the minute, the rotation of the robot is frame-dependent.
Changed: `minute` to `moment`
After:
>At the moment, the rotation of the robot is frame-dependent.
> fix: typo "minute" with "moment"

- course/lesson-13-conditions/lesson.tres
Fixed a typo.
Before:
We might want to want to display the health number on screen, like in Japanese RPGs.
Change: "want to want to" -> "want to"
After:
We might want to display the health number on screen, like in Japanese RPGs.
> fix: typo "want to want to"

- course/lesson-15-modulo/lesson.tres
Fix typos.
Before: `So 11% 4 is 3`
After: `So 11 % 4 is 3`
And:
Before: `For example, 1% 2 gives you 1.`
After: `For example, 1 % 2 gives you 1.`
> fix: missing space between a nr and modulo sign

- course/lesson-15-modulo/lesson.tres
Corrects the lesson text, so that it matches the example it's referring to.
In lesson 15:
https://gdquest.github.io/learn-gdscript/staging/#course/lesson-15-modulo/lesson.tres
Under the heading: `Three ways we use the modulo operation`
The example shows a traffic light.
Pressing the `Advance` button.
Cycles the lights from: `Red` to `Orange` to `Green`
then it repeats from `Red`
But the text below the example describes the color order as:
> The lights always cycle in the same way: first, we have the green light, then the orange, then the red.
**Expected**
The description, after matching the order in the example, results in:
> The lights always cycle in the same way: first, we have the …
> fix: traffic light colors, match example and text

- addons/SmoothScroll/SmoothScrollContainer.gd
This should help fix issues with touchpads firing too many scroll events on some web browsers.
Should fix #114 but needs testing.
> fix: throttle scroll events

- course/lesson-13-conditions/visuals/HealSprite.gd
- course/lesson-9-adding-and-subtracting/visuals/RobotCharacter.gd
Related issue (if applicable): #220 
Ensures that the health bars in lesson 9 and 13 show correct values when loaded in. 
For some reason the tween doesn't update it on load so it has to be set manually at first.
No
> fix: lesson 9 and 13 health bars now show proper values on ready

- ui/screens/lesson/UIBaseQuiz.gd
- ui/screens/lesson/UIBaseQuiz.tscn
- ui/screens/lesson/quizzes/UIQuizChoice.gd
- ui/screens/lesson/quizzes/UIQuizInputField.gd
Related issue (if applicable): #15 
Animates resizes of Quiz content blocks. Reacts upon any change of choice view or result view and will proceed to fit (if they are visible).
Almost the same as #234 except with proper spacing on some content.
This PR changes the Quiz Base UI to use a Control node with clip content on to contain margin containers. It reacts to the minimum size changes of the margin containers to determine the size it's supposed to animate to.
No
Instantaneous jumps to new size.
Animated size changes of rectangle size to fit the …
> improvement: animate quiz resizing

- course/lesson-5-your-first-function/TestsDrawingThreeSquares.gd
Related issue (if applicable): #256 
Adds a check to practice 2 in lesson 5 that will determine if there are too few or too many points in the polygon, showing a similar, yet more precise error message. Note that the user must have made 3 polygons for this to happen.
Most of these boil down to the draw_square function having been rewritten or draw square being called more than once in a row (with 3 successful polygons). Though I doubt the second reason would happen normally, hence why the error message asks for if the draw square function has been rewritten, and not if it was called twice.
No
> fix: added further checks to lesson 5 practice 2 with better error messages

- course/lesson-10-the-game-loop/rotating-and-moving/TestsRotatingAndMoving.gd
- course/lesson-10-the-game-loop/rotating-sprite/TestsRotating.gd
`_scene_root_viewport.get_child(0).get_child(0)` is returning the camera node so the validation scripts wouldn't work properly. This PR checks the correct node by retrieving it with `get_node()`
> fix(lesson10): Pick correct node to check in validation script

- ui/UICore.tscn
- ui/components/BigGreenButton.tscn
- ui/components/CodeEditor.tscn
- ui/components/popups/ConfirmPopup.gd
- ui/components/popups/ConfirmPopup.tscn
- ui/components/popups/ExternalErrorPopup.tscn
- ui/components/popups/LessonDonePopup.tscn
- ui/components/popups/PracticeDonePopup.tscn
- ui/components/popups/PracticeLeaveUnfinishedPopup.tscn
- ui/components/popups/PracticeListPopup.gd
- ui/components/popups/PracticeListPopup.tscn
- ui/components/popups/ReportFormPopup.tscn
- ui/components/popups/SettingsPopup.tscn
- ui/screens/course_outliner/CourseLessonDetails.tscn
- ui/screens/course_outliner/CourseLessonList.tscn
- ui/screens/lesson/UIPracticeButton.tscn
- ui/screens/welcome_screen/WelcomeScreen.tscn
- ui/theme/button_outlined_accent_hover.tres
- ui/theme/button_outlined_accent_normal.tres
- ui/theme/button_outlined_accent_pressed.tres
- ui/theme/button_outlined_hover.tres
- ui/theme/button_outlined_normal.tres
- ui/theme/button_outlined_pressed.tres
Changed a range of button themes for the ones that have borders. There are two states for:
- focus & hover: white color unless they're in a popup with green/red top-bar in which case the color is the same as the top bar for the cancel/confirm buttons depending on the case.
- normal: gray-blue color for all.
Pressed state is unchanged.
I also changed:
- how the `Start/Continue Course` looks on focus & hover to be consistent with the pop-ups.
- remove border blending on all button styles for consistency.
- add a `grab_focus()` on the cancel button for `/ui/components/popups/PracticeListPopup.gd` to be the same as the rest.
closes #346
> improve: make button theme consistent & less confusing

- course/lesson-17-while-loops/visuals/ExampleBoardWhile.tscn
- course/lesson-17-while-loops/visuals/ExampleRobotMoveRight.tscn
- course/lesson-17-while-loops/visuals/Robot.gd
- course/lesson-18-for-loops/visuals/ExampleBoardFor.tscn
When changing board size after the robot moves, make the character
stay inside the board.
fixes #371
> fix(lessons 17 18): constrain robot to board

- run
- ui/UICore.tscn
- ui/UIVersion.gd
- ui/theme/fonts/font_version.tres
- utils/version.gd
It also handles mouse clicks:
- hash goes to github hash version
- version number goes to the changelog file
closes #375
closes #376
> chore: add version info for desktop platforms

- course/lesson-24-access-array-indices/visuals/ExamplePrintSize.tscn
- course/lesson-24-access-array-indices/visuals/ExampleUseFirstItem.tscn
This commit also changes the *GDQuest Code* property for `ExamplePrintSize.tscn` to have matching inventory names to the randomly generated ones.
fixes #414
> fix(lesson24): match inventory order with visual textures

- project.godot
- ui/UINavigator.tscn
- ui/components/FullScreenButton.gd
- ui/components/FullScreenButton.tscn
- ui/components/QuitButton.gd
- ui/components/QuitButton.tscn
- ui/icons/quit.svg
- ui/icons/quit.svg.import
- ui/screens/end_screen/EndScreen.gd
- ui/screens/end_screen/EndScreen.tscn
- ui/screens/welcome_screen/WelcomeScreen.gd
- ui/screens/welcome_screen/WelcomeScreen.tscn
Reason I made this a draft is to confirm if the state should be saved and restored without user input. The state being: window size, window position and window fullscreen state. The current behavior is to save these to the user profile and restore it on subsequent runs.
If this is fine, only thing I'd do is add a reset button to the Settings panel to reset the state to the project default settings, in case someone wants to recenter the window or what-not.
closes #400
> improve: start in fullscreen mode by default

- course/lesson-15-modulo/visuals/ExampleModulo.tscn
- course/lesson-15-modulo/visuals/Modulo.gd
- course/lesson-15-modulo/visuals/Modulo.tscn
- course/lesson-15-modulo/visuals/Modulo/normal_stylebox.tres
- course/lesson-15-modulo/visuals/Modulo/remainder_stylebox.tres
- ui/components/RunnableCodeExample.gd
The example now looks like this:
https://user-images.githubusercontent.com/1177508/157216983-71bb1f6f-3e49-469f-a0ab-898ce4bb311b.mp4
To color-code the sliders I had to add a feature to  `RunnableCodeExample.create_slider_for()` to pass an optional color. This color overrides the color of the labels and the slider stylebox. It will also force only the highlight stylebox be visible at all times, even if the mouse doesn't hover over it.
closes #430
> improvement(lesson15): rethink color coding and box alignment

- course/lesson-11-time-delta/rotating-and-moving-delta/TestsRotatingMovingDelta.gd
Apologies, I wasn't able to find your commit message guidelines, so I just matched the styling to my best guess.
Similarly, it looks like the changelog is being handled as a prerelease activity; I did not make a new section with this small change.
Related issue (if applicable): #479
> fix: Handle optional parameters on move_local_x in lesson 11

- course/lesson-19-creating-arrays/moving-turtle/TestMovingTurtle.gd
Related issue (if applicable): #516 
Updated `test_path_is_contiguous` for lesson 19 to use the turtles starting
point when checking if the path is contiguous. This addresses the issue
if the user only provides one point in the array.
> fix: updated moving turtle test for lesson 19 to include the starting point

- course/lesson-11-time-delta/rotating-and-moving-delta/TestsRotatingMovingDelta.gd
Related issue (if applicable): #501
Updated the `test_movement_is_time_dependent` test function to check
if each of the code lines includes the `delta` substring.
> fix: delta check in the moving in a circle lesson

- .gitignore
- html_export/index_template.html
- html_export/static/style.css
- run
Related issues: 
- #532 
- #448
- fixes the CSS of the warning so it fits on any screen
- changes the message to remove the implication of "mobile" and focus on screen size only
- changes the detection logic to not care about aspect ratio, and only trigger under two conditions: either browser window width is under 700px, or height is under 400px, or the orientation is portrait (width < height).
Note: 700px and 400px are arbitrary values. In my personal tests, they seems to be the lowest value after which texts become uncomfortable.
If we want to target mobile users more aggressively with that notice, we can use the media queries `(pointer:none), (pointer:coarse), (hover:none), (hover:on-demand)` (based on [this SO answer](https://stackoverflow.com/questions/12469875/how-to-code-css-media-q …
> Screen size warning

- ui/components/CodeEditorEnhancer.gd
- utils/TextUtils.gd
Related issue (if applicable): #617 
**Needs testing with the Web build!**
Adds color highlight for bbcode keywords between [code] tags, using static regex's.
> Add color highlight for bbcode keywords (inside [code] tags)

- ui/UINavigator.gd
When clicking a button to navigate to a different screen multiple times quickly (sometthing users might do if the screen transition is slowish; I did this with a loading time of ~1sec), the next screen will appear repeatedly, causing a lag and bugging the breadcrumbs (only one instance of the next screen will appear in the breadcrumbs, not the whole stack of repeated screens). Lessons in particular will also appear with glitched text (probably something related to the bbcode formatting regex).
This fixes this behaviour. It creates a safe variable on _navigate_to() so it only navigates to the next screen after it finishes the transition the first time it was …
> Fix navigating multiple times

- ui/components/RunnableCodeExample.gd
- ui/components/RunnableCodeExample.tscn
Fix #661 
Enable "Clip Content" on Runnable Code Example container, and manually setting the Z-Index of buttons to 10 (an arbitrary number that is high enough so it won't conflict with the Node2D inside the example)
> Clip content of runnable code example

- script_checking/GDScriptCodes.gd
- script_checking/error_database.csv
Fix #625 
Adding an error when the user doesn't write a valid identifier in a `for` loop. Had to check when Godot throws this error, but it basically happens when the parser finishes interpreting an identifier after a `for` and it's expecting an `in`; so the user may have used punctuations or spaces in the identifier, or forgot to add an `in` to the `for` loop.
> Add IN_EXPECTED_AFTER_IDENTIFIER error

- i18n/extract.py
- i18n/match_and_merge_po_translations.py
> Write a script to split translation files with multiline translations into single-line ones

- course/lesson-3-standing-on-shoulders-of-giants/ExampleMoveSprite.tscn
- ui/components/RunnableCodeExample.gd
Fix #694 .
One problem that I also fix on this PR is the fact that examples now reset every time `run()` is pressed. I added this with the Debugger node because no code example with the debugger made sense to store the state of the variables between `run()`'s, and I needed to reset it to a default `unassigned` value. But some examples (specially the first ones) expect the user to play `run()` more than once with the previous state in mind (e.g. rotating a sprite).
What this PR does is to check when the user presses `run()` whether the example has a `debugger` node. If and only if it has, it resets.
> Fix Lesson 3 example and stop examples with no debuggers from resetting every `run()`.

- autoload/ThemeManager.gd
- resources/Profile.gd
- ui/components/popups/SettingsPopup.gd
- ui/components/popups/SettingsPopup.tscn
Related issue (if applicable): #623
Adds new Setting **Text Color** to the SettingsPopup to change the color of all (`Label ` and  `RichTextLabel` ) text in the app.
Color setting is also stored to the `Profile`.
Maybe its not the best idea to change `Label ` and  `RichTextLabel` or probably there are Control Nodes who should change color.
> feat: add option to change text color

- course/lesson-21-strings/visuals/ExampleCombo.tscn
Lesson 21 broke after the Debugger feature, since we are now using "yield()" to stop code execution in the examples. Fix #668.
> Fix yield() returning a GDScriptFunctionState to RunnableCodeExample

- course/lesson-21-strings/string_array/TestsStringArray.gd
When completing lesson 21, one does not need to call `play_animation()` in their for loop.
Related issue (if applicable): #739 
Add a check for the use of play_animation() in Lesson 21
No
> fix: Lesson 21 does not check for play_animation()

- course/lesson-21-strings/visuals/ExampleCombo.tscn
Related issue (if applicable): #799 
I'm assuming the 'Step' button being added to the final example in Lesson 21 was an accident - the code that looks for `yield()` to determine whether or not to add the 'Step' button to the example was catching the `yield()` that was commented out.
> fix: Lesson 21 - remove Step button from combo example

- course/lesson-28-specifying-types/lesson.tres
Related issue (if applicable): #844
Changes [] to Vector2(1, 1) in the starting code for lesson 28.
No
The starting code has [], but the tests check for Vector2(1, 1). And the solution uses Vector2(1, 1) as well.
The starting code has Vector2(1, 1)
> content: fix starting_code for lesson 28

- autoload/MessageBus.gd
Related issue (if applicable): #979 
see https://github.com/GDQuest/learn-gdscript/issues/979
The generated Script will look like:
```
extends Node2D
onready var _animation_tree := find_node("AnimationTree")
func _ready():
var i = 0
MessageBus.print_log([str(i], "WelcomeToTheApp", 6, 1))
yield(get_tree().create_timer(1.0), "timeout")
Events.emit_signal("practice_run_completed")
func _run():
_animation_tree.travel("saying_hi")
```
and due to `[str(i]` it will crash.
adapt the regex to search for the appropriate closing bracket
> improvement: adapt regex to search for the appropriate closing bracket

- ui/UIPractice.gd
Related issue (if applicable): #961
Currently the app will crash if you have more then one `while` loop in the `script_text` due to:
The generate code (`script_text`) looked like this:
```
func move_to_bottom():
var __guard_counter := 0
while cell.x < board_size.x - 1:
__guard_counter += 1
if __guard_counter > 100:
break
cell.x += 1
var __guard_counter := 0
while cell.y < board_size.y -1:
__guard_counter += 1
if __guard_counter > 100:
break
cell.y += 1
```
Change will define the variable `__guard_counter` just once and for other while loops it will be set back to 0.
Now the code looks like:
```
func move_to_bottom():
var __guard_counter := …
```
> fix: __guard_counter already defined in the scope

- course/lesson-13-conditions/limiting_health/TestLimitingHealth.gd
Related issue (if applicable): #622 
Currently the test "Health Takes Different Values" will fail with missleading message when an floatingpoint value is used for `health`
Also the test "Health Does Not Go Above 80" will wrongly pass when an floatingpoint values between 80.1 and 80.9 is set:
The test "Health Takes Different Values" will pass correctly even if "80" or "80.0" is set for `health`
Also test "Health Does Not Go Above 80" will fail correctly
> #622 error in 13. conditions limited healing

- ui/theme/fonts/font_button.tres
- ui/theme/fonts/font_button_big_green.tres
- ui/theme/fonts/font_button_small.tres
- ui/theme/fonts/font_code.tres
- ui/theme/fonts/font_code_small.tres
- ui/theme/fonts/font_documentation_bold.tres
- ui/theme/fonts/font_documentation_italics.tres
- ui/theme/fonts/font_documentation_mono.tres
- ui/theme/fonts/font_documentation_normal.tres
- ui/theme/fonts/font_lesson_heading.tres
- ui/theme/fonts/font_main_menu_buttons.tres
- ui/theme/fonts/font_percent.tres
- ui/theme/fonts/font_practice_progress.tres
- ui/theme/fonts/font_text.tres
- ui/theme/fonts/font_text_bold.tres
- ui/theme/fonts/font_text_bold_italics.tres
- ui/theme/fonts/font_text_italics.tres
- ui/theme/fonts/font_title.tres
- ui/theme/fonts/font_title_big.tres
- ui/theme/fonts/font_title_slim.tres
- ui/theme/fonts/font_title_small.tres
- ui/theme/fonts/font_version.tres
- ui/theme/fonts/font_well_done_bold.tres
- ui/theme/fonts/font_well_done_normal.tres
- ui/theme/fonts/font_well_done_title.tres
Related issue (if applicable): #497
Add some Traditional Chinese text to an Label with for example `font_documentation_bold.tres` as font.
> improvement: Add Chinese font
