course/lesson-7-member-variables/draw_rectangle_at_position/TestsDrawingRectangles.gd
course/lesson-7-member-variables/draw_rectangles_at_positions/TestsDrawingRectangles.gd

Related issue (if applicable): 
#80,  #67

fix: lesson 7's practice tests

---

ui/UIBaseQuiz.gd

Implemented the quiz error shake for better UI expirients.
No.
https://user-images.githubusercontent.com/1049442/147855732-219b438d-bbc6-430b-b792-915c80863b5d.mp4

feat: add a shake animation when failing at a quiz

---

ui/UINavigator.gd

Fix breadcrumbs lesson navigation index

---

ui/components/OutputConsole.gd

fix: the explanation error popup not centered with different screen resolutions

---

course/lesson-7-member-variables/content-UDpPwQDw.tres

This PR should fix a typo and deletes an unnecessary space I noticed while completing the course.

fix: fixed two small typos in lesson 7

---

course/lesson-1-what-code-is-like/content-109371.tres

Related issue (if applicable): #121
Am I understanding pull requests correctly now? / Have I done everything right?

content: make sentence more precise in lesson 1

---

course/lesson-5-your-first-function/practice-kGx0c7DD.tres

Expanded lesson text to clarify what function jump() does

Explain Jump

---

course/lesson-9-adding-and-subtracting/lesson.tres

fix: lesson 9 typo "Replaces" with "Replace

---

course/lesson-1-what-code-is-like/lesson.tres
course/lesson-10-the-game-loop/lesson.tres
course/lesson-11-time-delta/lesson.tres
course/lesson-12-using-variables/lesson.tres
course/lesson-13-conditions/lesson.tres
course/lesson-2-your-first-error/lesson.tres
course/lesson-3-standing-on-shoulders-of-giants/lesson.tres
course/lesson-5-your-first-function/lesson.tres
course/lesson-6-multiple-function-parameters/lesson.tres
course/lesson-7-member-variables/lesson.tres
course/lesson-8-defining-variables/lesson.tres
course/lesson-9-adding-and-subtracting/lesson.tres

Made some minor changes to the text of lessons 1-3 and 5-13.

content: minor text revisions

---

course/lesson-16-2d-vectors/increase_scale/TestScaleIncreased.gd

fix: typo, missing "like"

---

.github/ISSUE_TEMPLATE/bug_report.md

improvement: typos in issue template

---

course/lesson-16-2d-vectors/lesson.tres

Related issue (if applicable): #366

fix: Changed spelling of "directoin" to direction

---

course/lesson-17-while-loops/lesson.tres

fix: typos in lesson 17

---

course/lesson-22-functions-return-values/lesson.tres

fix: typo, lesson 22

---

course/lesson-23-append-to-arrays/lesson.tres

fix: typo, double space

---

autoload/NavigationManager.gd
course/glossary.csv
course/glossary.csv.import
course/glossary.tres
i18n/extract.py
project.godot
resources/Glossary.gd
ui/UILesson.gd
ui/UILesson.tscn
ui/components/GlossaryPopup.gd
ui/components/GlossaryPopup.tscn
ui/components/popups/ErrorOverlayPopup.tscn

feat: add course glossary

---

course/lesson-16-2d-vectors/lesson.tres
course/lesson-17-while-loops/lesson.tres
course/lesson-18-for-loops/lesson.tres
course/lesson-19-creating-arrays/lesson.tres
course/lesson-20-looping-over-arrays/lesson.tres
course/lesson-21-strings/lesson.tres
course/lesson-22-functions-return-values/lesson.tres
course/lesson-23-append-to-arrays/lesson.tres
course/lesson-24-access-array-indices/lesson.tres
course/lesson-26-looping-over-dictionaries/lesson.tres
course/lesson-27-value-types/lesson.tres
course/lesson-28-specifying-types/lesson.tres

text revisions

---

course/lesson-8-defining-variables/lesson.tres

Typo correction

---

ui/theme/gdscript_app_theme.tres
ui/theme/stylebox_empty.tres

Removed duplicated StyleBoxEmpty from theme resource. Used one external resource when StyleBoxEmpty is used.
No

chore: remove StyleBoxEmpty duplicates from theme

---

course/lesson-5-your-first-function/lesson.tres

Fix issue #570.
Related issue (if applicable): #570
change text in course/lesson-5-your-first-function/lesson.tres
no.
Replace rectangle with square.
the paragraph :
In this simple example, it may not feel super useful. Here's a more useful and realistic one: a function to draw any rectangle.
the paragraph should read:
In this simple example, it may not feel super useful. Here's a more useful and realistic one: a function to draw any square.
...

fix: replace rectangle with square in lesson 5

---

run

fixes #618
Should be tested on staging first

always use debug build

---

course/lesson-22-functions-return-values/lesson.tres

Adds text explanation to Lesson 22 to improve clarity on the conversion of Cell coordinate to screen position.

Improve Lesson 22 cell screen-position explanation

---

course/lesson-13-conditions/lesson.tres

Lesson 13: Ignore "type" word and remove whitespaces

---

course/lesson-22-functions-return-values/lesson.tres

Fix #581 
Change sentence regarding documentation in practices to improve clarity.

Improve clarity on lesson 22 content about documented functions

---

addons/gdscript-course-builder/ui/LessonPracticeHint.gd
resources/Glossary.gd

Related issue (if applicable): #555

improvement: load translation into glossary and practice hints

---

autoload/TranslationManager.gd
resources/Glossary.gd
ui/UILesson.gd

Related issue (if applicable): #685
Emit the "translation_changed" signal from the TranslationManager when the language is set.
Listen to this signal in UILesson.gd and trigger the new defined function `_underline_glossary_entries` for Underline glossary entries.

feat: make glossary entries work in other languages

---

course/lesson-15-modulo/traffic_lights/TrafficLights.tscn
course/lesson-15-modulo/visuals/DemoTrafficLights.tscn
course/lesson-15-modulo/visuals/ExampleModulo.tscn
course/lesson-15-modulo/visuals/ExampleTrafficLightsCondition.tscn
course/lesson-15-modulo/visuals/TrafficLightsCondition.gd
course/lesson-15-modulo/visuals/TrafficLightsCondition.tscn
course/lesson-15-modulo/visuals/TrafficLightsModulo.gd
course/lesson-15-modulo/visuals/TrafficLightsModulo.tscn

This PR fixes the Traffic Light example behavior in Lesson 15. It also improves clarity in the example (both visually and the code example shown).
Fix #679.

Fix Traffic Light example behavior in Lesson 15.

---

course/lesson-15-modulo/lesson.tres

Improves a note block title in lesson 15.
No

Improve lesson 15 note title

---

course/lesson-10-the-game-loop/lesson.tres
course/lesson-11-time-delta/lesson.tres
course/lesson-14-multiplying/visuals/GraphExp.tscn
course/lesson-14-multiplying/visuals/GraphLinear.tscn
course/lesson-2-your-first-error/lesson.tres
course/lesson-3-standing-on-shoulders-of-giants/lesson.tres
course/lesson-5-your-first-function/lesson.tres
course/lesson-7-member-variables/ExampleSetCharacterPosition.tscn
course/lesson-8-defining-variables/lesson.tres

Related issue (if applicable): #671
It suggests improvements to lessons 1 - 14
No

Suggested content improvements for lessons 1 - 14

---

course/lesson-16-2d-vectors/lesson.tres

The lesson requires you to create a function called reset_robot, if you create one called reset you get an error that the function is already defined.
A correction to the wording of lesson 16
No

fix: Correct hint text for lesson 16

---

course/lesson-9-adding-and-subtracting/lesson.tres

Modified lesson.tres for lesson 9 to make paragraph 2 more easily understandable (from a lingual standpoint) #806 and fixed a typo (subtract to -> subtract from)

content: correct typo in lesson 9, improve wording

---

course/lesson-18-for-loops/visuals/PrintForLoopArrayUnwrapped.tscn

Related issue (if applicable): #798

fix: Lesson 18 - fix unwrapped loop resetting

---

README.md

Update documentation.
No
Add `content:` to valid prefixes as is the most used for typos in the project (not documentation).  
https://github.com/GDQuest/learn-gdscript/commit/6f52f8f76c3b03fefe8a99fe9aec7398f94e02bd
https://github.com/GDQuest/learn-gdscript/commit/0f14045899487b7d0601a3ae0dae687424af1adb
https://github.com/GDQuest/learn-gdscript/commit/c5aa408a560831b992d8b9337f19b74e08dbcfb0
https://github.com/GDQuest/learn-gdscript/commit/a02c2bae8512d26bbba34add57d78901c127f0d2
https://github.com/GDQuest/learn-gdscript/commit/1cf42f733c5bd0a207ce8ca58cfbd95bf4a0bf04 …

docs: add `content:` to valid prefixes

---

course/lesson-15-modulo/visuals/TrafficLightsCondition.gd
course/lesson-15-modulo/visuals/TrafficLightsModulo.gd
ui/components/RunnableCodeExample.gd

Related issue (if applicable): #795 
First contribution to this repo!

fix: Lesson 15 - fix traffic light resetting

---

course/lesson-7-member-variables/lesson.tres

A small fix in the explanation of Lesson 7
No
Here's what's currently incorrect, it refers to the above code but with the wrong data:

content: lesson 7 explanation fix

---

course/lesson-24-access-array-indices/visuals/ExampleUseFirstItem.tscn

Related issue (if applicable): #879 
It adds comma after the array elements which are dynamically added.
No
**After Changes:**

fix: Adding commas after array elements in Lesson 23

---

course/lesson-3-standing-on-shoulders-of-giants/lesson.tres

Related issue (if applicable): #990 
Reordered hints
No
Change
Hints are in the wrong order for lesson 3 practice exercise 2
Corrected order of hints for lesson 3

content: lesson 3 hint ordering fix

---

course/lesson-21-strings/string_array/TestsStringArray.gd

Related issue (if applicable): #920 
Improvement of `test_use_for_loop` (course\lesson-21-strings\string_array\TestsStringArray.gd) to check that the iterator is used.
See #920 
The test will fail with message that the iterator was not used:

fix: improve test_use_for_loop to check if the iterator is used

---

course/lesson-25-creating-dictionaries/creating-inventory/TestInventory.gd

fix #904 
See #904 
App will crash due to error:
`Invalid get index 'extra' (on base: 'Dictionary').`
App will not crash and tests will fail correctly.

fix: reverse logic, should checked that desired_inventory has all keys

---

course/lesson-6-multiple-function-parameters/lesson.tres
i18n/de/lesson-6-multiple-function-parameters.po
i18n/es/lesson-6-multiple-function-parameters.po
i18n/fr/lesson-6-multiple-function-parameters.po
i18n/it/lesson-6-multiple-function-parameters.po
i18n/ja/lesson-6-multiple-function-parameters.po
i18n/nl/lesson-6-multiple-function-parameters.po
i18n/pt/lesson-6-multiple-function-parameters.po
i18n/pt_BR/lesson-6-multiple-function-parameters.po
i18n/ru/lesson-6-multiple-function-parameters.po
i18n/tr/lesson-6-multiple-function-parameters.po
i18n/zh_Hans/lesson-6-multiple-function-parameters.po

Related issue (if applicable): #1020

Content: Correct dbl space in l6 mult func param
